import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav";
import ConnectWalletModal from "../components/ConnectWalletModal";

export default function Home() {
  const [walletOpen, setWalletOpen] = useState(false);
  const [step, setStep] = useState(0);

  function openWalletModal() {
    console.log("open wallet");
    setStep(0);
    setWalletOpen(true);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Connect Wallet Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Nav openWalletModal={openWalletModal} />
        <ConnectWalletModal
          walletOpen={walletOpen}
          setWalletOpen={setWalletOpen}
          step={step}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
